version: "3"

services:
  airflow:
    image: puckel/docker-airflow 
    ports:
      - "8080:8080"

    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8

  postgre:
    image: postgres:12.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      - TZ=Asia/Seoul
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data