version: "3"

services:
  airflow:
    build: ./docker_airflow
    depends_on:
      - postgre
    ports:
      - "8080:8080"

    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
      - FERNET_KEY="uE019HG1yZus7W414ZeHAmmGIF7CmW7WXBkOYpYKnak="
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgre:5432/airflow
    volumes:
      - "./dags:/usr/local/airflow/dags"

  postgre:
    build: ./docker_postgre
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      - TZ=Asia/Seoul
    volumes:
      - "/var/lib/postgresql/data:/var/lib/postgresql/data"
